### ISSUE TITLE
Crash when switching seats in a multi-car roller coaster train

### ISSUE THREAD

**Issue by fredtargaryen** [fredtargaryen/ExRollerCoaster_Old#17]
Not yet reproduced.

**Comment by darthvader45** [comment]
I've had it happen pretty consistently, just place a regular car, then a connector car on a section behind it. Then get in one of them and attempt to right-click the other.  Had it happen twice.

**Comment by fredtargaryen** [comment]
Hi, don't know if you're still using this mod but I'm looking into this now. I have been able to place a standard coaster, attach connector coasters, and right-click to switch between them easily.

However I've had problems getting into connector coasters which aren't connected to a coaster, which I have now fixed. Does this sound like what you are describing?

**Comment by darthvader45** [comment]
Huh, maybe that's it.  I'll check with the latest version and see.

**Comment by fredtargaryen** [comment]
Closed due to inactivity.
