### ISSUE TITLE
Two things.

### ISSUE THREAD

**Issue by melody-rs** [fredtargaryen/ExRollerCoaster_Old#18]
I think someone has reuploaded this to curseforge.
There is a crash when placing down the coaster cart.

**Comment by fredtargaryen** [comment]
Hi, thanks for getting in touch!
1. Thanks for letting me know. I already left a comment on the post telling them to at least give me credit and they just deleted the comment - a move I wasn't expecting. I'll explain the situation to CurseForge when I have the time, then upload the port on my own account I guess.

2. Oh no, I really thought I had fixed this. Do you have a crash log you can send me? It would be a big help.

**Comment by melody-rs** [comment]
Yeah sure! Apparently using older versions of forge and using optifine fixes it.
Is it ok if I include this in a modpack btw?
[crash-2020-06-14_21.39.37-client.txt](https://github.com/fredtargaryen/ExRollerCoaster_Old/files/4789597/crash-2020-06-14_21.39.37-client.txt)

**Comment by fredtargaryen** [comment]
Thanks for the log! I wouldn't have expected Optifine to fix it but... ok... I'm leaving this open as a reminder to myself to improve the rendering and riding aspects anyway.

You're welcome to use it in a modpack though it's not the most stable thing in the world...

**Comment by melody-rs** [comment]
I have yet to test if optifine fixes it, and I'll see if it does

**Comment by melody-rs** [comment]
nvm optfine doesn't fix it

**Comment by melody-rs** [comment]
Apparently using older versions of forge actually fixes it

**Comment by melody-rs** [comment]
How long do you think it'll take for you to fix it? The bug only happens on versions of forge past forge-1.12.2-14.23.5.2838, so there must've been a change that causes the model to be invalid in the next versions

**Comment by melody-rs** [comment]
When do you think you can get this fixed by?

**Comment by fredtargaryen** [comment]
Hi, sorry for not keeping you posted. Having trouble getting Forge set up on my computer right now. I'll let you know when I've figured that out and can start looking into the actual error.

**Comment by melody-rs** [comment]
Its ok! Is recommend using multimc since it can switch between forge versions really quickly.

**Comment by fredtargaryen** [comment]
Hi, sorry about the huge delay on this.

[Here is a test jar](https://fredtargaryen.github.io/files/ExRollerCoaster-1.5.1-test.jar?raw=true); please could you try this on your original Forge version and let me know whether or not this fixes your second problem?

(With regard to the first problem, the reupload was taken down but communication with CurseForge sort of broke down so I can't upload the mod under my name. I'll try again when Overwolf takes over fully)

**Comment by Speak2Erase** [comment]
Ok I'll test it out!

**Comment by melody-rs** [comment]
Yeah that fixed it
~~also sorry for not getting back to you in 15 days~~

> (With regard to the first problem, the reupload was taken down but communication with CurseForge sort of broke down so I can't upload the mod under my name. I'll try again when Overwolf takes over fully)

Makes sense

**Comment by fredtargaryen** [comment]
Great! Thanks for letting me know.
