### ISSUE TITLE
Distribution permission

### ISSUE THREAD

**Issue by pacas00** [fredtargaryen/ExRollerCoaster_Old#20]
Hi, Sorry to bother you, 

I found this mod via a friend linking me to the reddit page as they want me to include it in a modpack I'm building for them, And was wondering if you had ever managed to get permission to distribute the mod?

**Comment by fredtargaryen** [comment]
Hi! I've never received permission to do that.

**Comment by pacas00** [comment]
Alright, Thanks for your answer and taking the time to answer.

Stay safe and Happy Holidays.

**Comment by fredtargaryen** [comment]
You too; good luck with the pack!
